### PR TITLE
uncheck by default share contacts when pairing with bluetooth

### PR DESCRIPTION
**Pull request by dd-dreams**
solves https://github.com/GrapheneOS/os-issue-tracker/issues/2339

### CODE REVIEW

**Comment by thestinger** [comment]
@dd-dreams Is it possible this is already the default? In what situation is it enabled by default right now?

**Comment by dd-dreams** [comment]
It is the default when the pairing happens in the background, otherwise it's caused by user interaction which then shows the checkbox.

**Comment by empratyush** [comment]
> shows the checkbox.

alright but checkbox is deselected by default.

**Comment by dd-dreams** [comment]
No. See this: https://github.com/GrapheneOS/platform_packages_apps_Settings/blob/794bfba3d82f2af42e6928d53184d4ea7172ed1e/src/com/android/settings/bluetooth/BluetoothPairingDialogFragment.java#L261C9-L261C80

**Comment by empratyush** [comment]
Umm yes, but in [my testing checkbox is unselected by default](https://youtu.be/Jjz_qslRsmM). Can you confirm in your case checkbox is checked.

**Comment by empratyush** [comment]
LGTM

**Comment by dd-dreams** [comment]
> [my testing checkbox is unselected by default](https://youtu.be/Jjz_qslRsmM)

It seems though that your headphones are not necessarily "hands-free". It will probably usually happen with cars (maybe, not sure).

**Comment by thestinger** [comment]
This does not appear to be fully fixed. See https://discuss.grapheneos.org/d/16226-bluetooth-shares-contacts-and-calls-history-despite-being-turned-off-by-default/11. Someone there filed an issue on the tracker claiming we introduced the vulnerability with this change but we clearly didn't do that. We just need to extend the change to fully fix it.

**Comment by thestinger** [comment]
I've attempted to fix it in https://github.com/GrapheneOS/platform_packages_apps_Settings/commit/f47cbc0c239d20d5805643799728ee536ccecaa8.

**Comment by dd-dreams** [comment]
That's weird because https://github.com/GrapheneOS/platform_packages_apps_Settings/blob/ae03cce1992df91c333cf966813925d495465a67/src/com/android/settings/bluetooth/BluetoothPairingDialogFragment.java#L261  what sets if its checked or not, and it's being called after `setContactSharingState`.

**Comment by muhomorr** [comment]
@dd-dreams Check how `mPbapAllowed` is updated and used.

**Comment by dd-dreams** [comment]
Well it always seemed like `getContactSharingState` and `setContactSharingState` operated independently. Although this PR didn't try to fix what was said on the forum.

**Comment by thestinger** [comment]
@dd-dreams I was aware of the forum thread and previous discussions about it. Therefore, I thought this was an attempt at resolving those issues rather than only changing the default since it already always appeared to be set to off. That's why Pratyush asked those initial questions about it. I shouldn't have merged it without a full understanding of this.

**Comment by dd-dreams** [comment]
A reference would be nice before. Anyway the issue existed so the checkbox probably was not always set to off. Atleast it uncovered the issue in foreground :D

**Pull request merged**
