### PR TITLE
disable navigation option while setup is incomplete.

### PR DESCRIPTION
**Pull request by empratyush**
settings app does not check for user setup is completed or not and that lead to issue [#449](https://github.com/GrapheneOS/os-issue-tracker/issues/449).
although opening settings while setup is incomplete is not a good idea but current setup wizard does that. 
this patch should fix this behavior.

### CODE REVIEW

**Comment by thestinger** [comment]
Does the app get automatically respawned when setup is complete? Otherwise, it seems like navigation would remain disabled if you switched to the Settings app immediately afterwards without explicitly closing it.

**Comment by empratyush** [comment]
> Does the app get automatically respawned when setup is complete? Otherwise, it seems like navigation would remain disabled if you switched to the Settings app immediately afterwards without explicitly closing it.

In my testing yes.

It work because activity gets destroyed when it send result and reopening app when setup is completed does not lock nav options.

**Comment by flawedworld** [comment]
> > Does the app get automatically respawned when setup is complete? Otherwise, it seems like navigation would remain disabled if you switched to the Settings app immediately afterwards without explicitly closing it.
> 
> In my testing yes.
> 
> It work because activity gets destroyed when it send result and reopening app when setup is completed does not lock nav options.

I have not been able to reproduce this.

**Comment by empratyush** [comment]
> I have not been able to reproduce this.

wdym? I mean settings nav options were locked after setup is completed or not? (it shouldn't stay locked)

@thestinger btw implementation has been improved.

**Pull request closed without merging**
