### PR TITLE
remove misleading "backed up" phrase from storage manager

### PR DESCRIPTION
**Pull request by x86pup**
there's no code that checks for any kind of backup service, this is misleading

Solves https://github.com/GrapheneOS/os-issue-tracker/issues/2137

### CODE REVIEW

**Comment by thestinger** [comment]
Can we just disable it?

**Comment by x86pup** [comment]
Can hide the setting, but would need to figure out a way to migrate people's settings to disable it so they aren't stuck with it enabled if they have it turned on.

Or could just remove most of the feature so don't need to worry about migrating people's settings.

**Comment by thestinger** [comment]
I think there's a way to outright disable it via a resource. I remember someone asked us to enable it at some point. I guess that's gone now and it's enabled by default. Unsure.

**Comment by x86pup** [comment]
Can't seem to find the relevant resource. We probably just need to hide it and somehow migrate people's settings

**Comment by sysxda** [comment]
> Can we just disable it?

config_show_smart_storage_toggle

**Comment by x86pup** [comment]
I don't think that would migrate people's settings to turn it off. We can't just hide it or people will be stuck with it enabled if they already do.

**Comment by x86pup** [comment]
[`config_show_smart_storage_toggle` just hides the setting (availability)
](https://cs.android.com/android/platform/superproject/+/master:packages/apps/Settings/src/com/android/settings/deviceinfo/storage/AutomaticStorageManagementSwitchPreferenceController.java;l=70?q=config_show_smart_storage_toggle)
Yes it could be set to false but that doesn't migrate people's settings.

**Pull request closed without merging**
