### PR TITLE
Settings: Set flashlight to 100%/maximum

### LINKED ISSUE #4473: Increase flashlight brightness to maximum by default instead of 50%.
GrapheneOS should change this AOSP behaviour. Currently the only way to have the flashlight shine with max brightness is to open it from the Camera app.

### PR DESCRIPTION
**Pull request by neelchauhan**
Closes https://github.com/GrapheneOS/os-issue-tracker/issues/4473

### CODE REVIEW

**Comment by An-anonymous-coder** [comment]
Hey, just out of curiosity, could you explain what the new code does, how it works, and why it works?

**Comment by neelchauhan** [comment]
It's based off this API: https://source.android.com/docs/core/camera/torch-strength-control

In that document, it describes the function `turnOnTorchWithStrengthLevel()` and the maximum brightness which we set to `CameraCharacteristics.FLASH_INFO_STRENGTH_MAXIMUM_LEVEL`.

**Comment by WaleedMortaja** [comment]
`if (state == true)` seems to be redundant comparison. Would not `if (state)` be better? Or renaming the variable to be more meaningful, and so easier to read as, for example, `final boolean isFlashlightEnabled = ...`, then `if (isFlashlightEnabled)`

**Comment by neelchauhan** [comment]
> `if (state == true)` seems to be redundant comparison. Would not `if (state)` be better? Or renaming the variable to be more meaningful, and so easier to read as, for example, `final boolean isFlashlightEnabled = ...`, then `if (isFlashlightEnabled)`

I removed the `== true`. However I won't do `isFlashlightEnabled` mainly because `state` came from AOSP not Graphene.

**Comment by An-anonymous-coder** [comment]
Maybe also change `cameraManager.setTorchMode(cameraId, state);` to `cameraManager.setTorchMode(cameraId, false);`, since `state` in this case will always be `false`.

**Comment by neelchauhan** [comment]
Done!

**Comment by An-anonymous-coder** [comment]
I love how we're picking apart the simplest bit of code ;P

**Comment by neelchauhan** [comment]
Unfortunately, this PR doesn't set the maximum brightness despite it telling it to after testing on a Pixel 8a. I probably need the `CameraControl` class here instead.

**Comment by neelchauhan** [comment]
I'll close this as this PR doesn't work, but this actually works when done in `frameworks/base`: https://github.com/GrapheneOS/platform_frameworks_base/pull/81.

**Pull request closed without merging**
