### PR TITLE
Apps with background access: sort application info list for access sensors and clipboard activities

### PR DESCRIPTION
**Pull request by rascarlo**
- OtherSensorsBackgroundActivity: sort application info list
- ReadClipboardBackgroundActivity: sort application info list

### CODE REVIEW

**Comment by thestinger** [comment]
This should probably do AccessLocationBackgroundActivity and RecordAudioBackgroundActivity too for consistency.

**Comment by rascarlo** [comment]
Those two others activities have the list sorted already.

**Comment by thestinger** [comment]
Ah, I see, must have been missed during development.

**Comment by thestinger** [comment]
Thanks. I'll probably split this into 2 commits later on though.

**Pull request merged**
